services:
  openinvento:
    image: ghcr.io/openinvento/openinvento:${OPENINVENTO_VERSION}
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      DATA_DIRECTORY: /data
      APP_URL: ${APP_URL} # Set this to the URL where the container will be accessible (e.g., http://localhost:80)
    volumes:
      - openinvento-data:/data

volumes:
  openinvento-data: