[project]
name = "openinvento"
version = "0.1.0"
description = "Source available inventory app"
requires-python = ">=3.12"
license = { text = "PolyForm Shield License 1.0.0" }

# List all your production dependencies here
dependencies = [
    "django>=6.1.1",
    "uvicorn>=0.28.0",
    "djangorestframework==3.18.0",
    "Pillow==12.3.0",
    "django-ratelimit==4.1.0"
]

[tool.setuptools]
packages = []