# Generated by Django 6.0.3 on 2026-09-13 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_default_categories(apps, schema_editor):
    Inventory = apps.get_model("inventory", "Inventory")
    ArticleCategory = apps.get_model("inventory", "ArticleCategory")
    CategoryField = apps.get_model("inventory", "CategoryField")
    defaults = {
        "Food": ({"key": "barcode", "label": "Barcode", "field_type": "barcode"},),
        "Books": ({"key": "author", "label": "Author", "field_type": "text"},),
    }
    for inventory in Inventory.objects.all():
        for name, fields in defaults.items():
            category, _ = ArticleCategory.objects.get_or_create(inventory=inventory, name=name)
            for field in fields:
                CategoryField.objects.get_or_create(
                    inventory=inventory,
                    category=category,
                    key=field["key"],
                    defaults={"label": field["label"], "field_type": field["field_type"]},
                )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CategoryField',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('identifier', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField()),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('barcode', 'Barcode')], default='text', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='inventory.articlecategory')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('inventory', 'key', 'category'), name='unique_category_field')],
            },
        ),
        migrations.RunPython(create_default_categories, migrations.RunPython.noop),
    ]
