name: CLA Check

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - closed

  issue_comment:
    types:
      - created

  workflow_dispatch:
    inputs:
      pr_number:
        description: Pull request number to recheck
        required: true
        type: string

permissions:
  contents: read
  issues: write
  pull-requests: read
  actions: write

jobs:
  cla:
    name: CLA Check
    runs-on: ubuntu-latest

    steps:
      - name: Check CLA
        uses: openinvento/cla-bot@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cla-token: ${{ secrets.CLA_BOT }}
          cla-version: v1
          cla-repository: openinvento/openinvento-cla
          cla-file: agreements/signatures.json
          workflow-file: cla.yml